# Basic `dependabot.yml` file with
# minimum configuration for two package managers

version: 1
updates:
  # Enable version updates for cargo
  - package-ecosystem: "cargo"
    # Look for `Cargo.toml` and `lock` files in the `root` directory
    directory: "/"
    # Check the cargo registry for updates every day (weekdays)
    schedule:
      interval: "daily"
