[umu]
prefix = "~/.config/hoyoplay-umu/wine_prefix"
proton = "~/.config/hoyoplay-umu/ProtonLatest"
game_id = "hoyoumu"
exe = "~/.config/hoyoplay-umu/wine_prefix/drive_c/Program Files/HoYoPlay/launcher.exe"

[env]
PROTON_VERB = "waitforexitandrun"

