[umu]
prefix = "~/.config/hoyoplay-umu/wine_prefix"
proton = "~/.config/hoyoplay-umu/Proton-GE_Latest"
title = "Genshin Impact"
store =	"none"
game_id = "umu-genshin"
codename = "none"
exe = "~/.config/hoyoplay-umu/wine_prefix/drive_c/Program Files/HoYoPlay/launcher.exe"

[env]
PROTON_VERB = "waitforexitandrun"
